version: '3'

services:
  django:
    build: .
    container_name: django_proj
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      hfnet:
        ipv4_address: 172.23.0.2